# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui import waterMarkWindow
from ui import renameWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(560, 238)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./image/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_watermark_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_watermark_button.setGeometry(QtCore.QRect(30, 30, 111, 41))
        self.open_watermark_button.setObjectName("open_watermark_button")
        self.open_rename_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_rename_button.setGeometry(QtCore.QRect(30, 90, 111, 41))
        self.open_rename_button.setObjectName("open_rename_button")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(210, 20, 304, 139))
        self.image_label.setObjectName("image_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片助手"))
        self.open_watermark_button.setText(_translate("MainWindow", "添加水印"))
        self.open_rename_button.setText(_translate("MainWindow", "批量重命名"))
        self.image_label.setText(_translate("MainWindow", "TextLabel"))
        self.image_label.setPixmap(QtGui.QPixmap("./image/logo——.png"))
